// BOOK
export const BOOK_FETCHING = "BOOK_FETCHING";
export const BOOK_SUCCESS = "BOOK_SUCCESS";
export const BOOK_FAILED = "BOOK_FAILED";
export const BOOK_CLEAR = "BOOK_CLEAR";
export const FETCHOPTION_SUCCESS = "FETCHOPTION_SUCCESS";
